## Configuracion de Instancia
server:
  port: 8081
  error:
    include-stacktrace: on_param

## Configuracion de Spring
spring:
  application:
    name: ms-books-users
  datasource:
    url: jdbc:mysql://${ENDPOINT_DB_PAYMENTS:localhost}:3306/users
    username: ${USER_DB_PAYMENTS:root}
    password: ${PASS_DB_PAYMENTS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: UserPool
      auto-commit: false
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-users


